name = "uml2code"
description = "UML to Ada code generator"
version = "0.1.0-dev"
licenses = "BSD-3-Clause"
authors = ["Joe Beazelman"]
maintainers = ["Joe Beazelman <joe@example.com>"]
maintainers-logins = ["Joebeazelman"]
website = "https://github.com/Joebeazelman/uml2code"
tags = ["uml", "code-generation", "ada"]

[[depends-on]]
plantuml_parser = "*"
uml_model = "*"
jintp = "*"
aunit = "*"

[[actions]]
type = "test"
command = ["sh", "-c", "alr exec -- gprbuild -P tests/uml2code_tests.gpr -p && ./tests/obj/tests"]

[[pins]]
#jintp = { path='../JinTP' }
uml_model = { path='../uml_model' }
plantuml_parser = { path='../plantuml_parser' }
string_utilities = { path='../string_utilities' }
