# ada/manifest.ini -- template set descriptor

[set]
name      = ada
language  = Ada
extension = .ads

[code-spec]
class         = class.tpl
relation      = relation.tpl
state_machine = state_machine.tpl

[code-body]
class         = class_body.tpl

[test-spec]
class         = class_tests.tpl
state_machine = state_machine_tests.tpl

[test-body]
class         = class_tests_body.tpl
state_machine = state_machine_tests_body.tpl

[context]
class         = name, visibility, attributes, operations
relation      = kind, source, target, source_role, target_role, multiplicity
state_machine = name, states, transitions, initial
